### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by flavio**
I noticed there's no automation on this repository. This PR covers the basics, I hope you won't mind it :blush: 

Add the following GitHub actions to:

  * Run unit tests on PR and on push events
  * Look for security issues via `cargo audit` on a daily basis (cron)
  * Look for security issues via `cargo audit` whenever the Cargo.* file
    are changed

### CODE REVIEW

**Comment by jsoverson** [comment]
Thanks @flavio!

**Comment by jsoverson** [comment]
I don't have write access to this repo but I've poked @pkedy for the merge.

**Comment by pkedy** [comment]
I'd like @autodidaddict to review this because he knows his Rust.

**Review by autodidaddict — APPROVED** [review]

**Comment by flavio** [comment]
@pkedy / @autodidaddict : can somebody merge it? :pray:

**Comment by autodidaddict** [comment]
Hmm with my approval you should've been able to merge.

**Pull request merged**
